### ISSUE TITLE
Item selected at true but still showing default title

### ISSUE THREAD

**Issue by fleflochN** [dbilgili/Custom-ReactJS-Dropdown-Components#5]
Hello,

not sure if this is an issue or just a feature which isn't developped but here is my problem.
When building a DropDown I flag one of the item as selected, but the title is still showing the default title and not the key of the selected item.
I can confirm that the item is selected since when opening the dropdown it shows the ticker right to the item key.
I thought that maybe it was triggering a method internally to automatically display the item's key instead of the default title when an item is flagged as selected. 
Do I have to change the default title myself ?

Thank you.

**Comment by dbilgili** [comment]
`<DropDown/>` component has an internal method named `selectItem()` which sets the `headerTitle` state to the title of the selected item.

If you have installed the npm package, there is not much you can do about it. However, you can always add the [DropDown](https://github.com/dbilgili/Custom-ReactJS-Dropdown-Components/blob/master/src/components/Dropdown.js) component in your project manually and import it from your directory. Then just define the default props as follows inside the `DropDown` component.

```
Dropdown.defaultProps = {
  title: 'Apple',
}
```

Where `Apple` is the item in the list, which has its `selected` key set to `true` by default.

Last thing is to drop the `title` prop when using `<DropDown>` component.

```
<Dropdown
  list={this.state.fruit}
  resetThenSet={this.resetThenSet}
/>
```

Hope that helps 👍

**Comment by fleflochN** [comment]
Hello @dbilgili ,

Great I'll use this feature !
Thank you for your answer.

**Comment by fleflochN** [comment]
Hum weird stuff.
If I change the title and render my component the title isn't changed. It always display the title indicated in the first render of the component...
Am I doing something wrong ? The component doesn't seem to be re-rendered...

**Comment by dbilgili** [comment]
Ok, so as far as I understand, you want to provide a list of items with one of them selected by default. If your case is that simple, then the above mentioned method should suffice, although it's not a nice solution.
However, if you are dynamically changing the list without using the dropdown menu and want to have this reflected to dropdown, then you have to pick the title of this selected value and use it for `title` prop on `<Dropdown/>`. However, this will also needs some tweaks on the inner dynamics of the component.

- In `Dropdown` component, drop the `headerTitle` state and also remove the related `setState` lines and use `title` prop in the `render()` method instead of `headerTitle`.

- Add a state like `title` in the parent component of `<Dropdown/>`.

- Add the following method to your parent component.

```js
  setTitle = () => {
    const item = this.state.fruit.find(item => item.selected);
    this.setState({title: item.title});
  }
```

And call it in `componentDidMount()` and as a callback to `setState` of `resetThenSet()` method.

```js
  componentDidMount() {
    this.setTitle();
  }

  resetThenSet = (id, key) => {
    let temp = JSON.parse(JSON.stringify(this.state[key]))
    temp.forEach(item => item.selected = false);
    temp[id].selected = true;
    this.setState({
      [key]: temp
    }, this.setTitle)
  }
```

And of course you have to call the `setTitle()` method as a callback whenever you set your list state.

If that doesn't do the trick for you, try to share a sample code through `codesandbox`, `glitch` etc.

**Comment by fleflochN** [comment]
Hello,

thank you for taking the time to answer !
Let me check on my side to see if I can fix the issue with the informations provided and I'll come back here to let you know if I finally managed to fix it.

**Comment by fleflochN** [comment]
I managed to make everything work following your advice.
The downside of it is that I need to have my own version of the component so I won't be able to update the component easily.
Thank you for your help.
